version: '3'
services:
  laravel.test:
    image: 'laravel/sail:latest'
    container_name: laravel-app
    ports:
      - '8080:80'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailpit
      - selenium
    working_dir: /var/www/html

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail

  redis:
    image: redis:alpine
    networks:
      - sail

  meilisearch:
    image: getmeili/meilisearch:latest
    networks:
      - sail

  mailpit:
    image: axllent/mailpit:latest
    networks:
      - sail

  selenium:
    image: selenium/standalone-chromium
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
